import type { GadgetSettings } from "gadget-server";

export const settings: GadgetSettings = {
  type: "gadget/settings/v1",
  frameworkVersion: "v1.1.0",
  plugins: {
    connections: {
      shopify: {
        apiVersion: "2024-04",
        enabledModels: [
          "shopifyApp",
          "shopifyAppCredit",
          "shopifyAppInstallation",
          "shopifyAppPurchaseOneTime",
          "shopifyAppSubscription",
          "shopifyAppUsageRecord",
          "shopifyAsset",
          "shopifyBillingAddress",
          "shopifyBulkOperation",
          "shopifyCart",
          "shopifyCartLineItem",
          "shopifyCheckout",
          "shopifyCheckoutAppliedGiftCard",
          "shopifyCheckoutLineItem",
          "shopifyCheckoutShippingRate",
          "shopifyCollect",
          "shopifyCollection",
          "shopifyDomain",
          "shopifyFile",
          "shopifyFulfillment",
          "shopifyOrder",
          "shopifyProduct",
          "shopifyProductImage",
          "shopifyProductOption",
          "shopifyProductVariant",
          "shopifySellingPlan",
          "shopifySellingPlanGroup",
          "shopifySellingPlanGroupProduct",
          "shopifySellingPlanGroupProductVariant",
          "shopifyShippingAddress",
          "shopifyTheme",
        ],
        type: "partner",
        scopes: [
          "read_orders",
          "read_customer_merge",
          "write_customer_merge",
          "read_audit_events",
          "read_products",
          "write_products",
          "read_themes",
          "write_themes",
          "read_customer_events",
          "read_fulfillments",
        ],
      },
      openai: true,
    },
  },
};
